---
label: Recipe
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: file
  name: featureImg
  label: Featured Img
- type: text
  name: youtubeId
  label: Video ID from Youtube
  description: Just the ID number, not the full URL
- type: textarea
  name: source
  label: Source URL
  description: The full URL to the source of the recipe.
- type: text
  name: summary
  label: Summary
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: featureImgAttr
  type: text
  config:
    required: false
  label: Image Credit
  description: The URL of the site to credit for featured image.
- name: ingredients
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: false
    label: Name
  - name: amount
    type: text
    config:
      required: false
    label: Amount
  config:
    min: 
    max: 
    labelField: 
  label: Ingredients
pages:
- recipes/cashew-ice-cream-base.md
- recipes/chimichurri.md
- recipes/coconut-curry-with-tofu-potatoes.md
- recipes/lettuce-wraps.md
- recipes/mac-and-peas.md
- recipes/pasta-with-chickpeas.md
- recipes/pie-dough.md
- recipes/pizza-dough-neapolitan-style.md
- recipes/sichuan-mala-noodles.md
- recipes/veg-kurma.md
- recipes/warm-potato-salad-with-chimichrri-crispy-chickpeas.md
