---
label: Recipe
hide_body: false
fields:
- type: text
  name: title
  label: Title
- type: file
  name: featureImg
  label: Featured Img
- type: text
  name: youtubeId
  label: Video ID from Youtube
  description: Just the ID number, not the full URL
- type: textarea
  name: source
  label: Source URL
  description: The full URL to the source of the recipe.
- type: text
  name: summary
  label: Summary
- type: list
  name: ingredients
  label: ingredients
  config:
    use_select: false
- name: tags
  type: tag_list
  default: []
  label: Tags
